### ISSUE TITLE
Needs to be looked into: Converting tool won't work when `.html` file is specified

### ISSUE THREAD

**Issue by bpires** [mdn/markdown#47]
Hi, I've searched the MDN's repos and this one seemed the more appropriate to open this issue.

During the '100% Markdown Hackday' we left with some takeaways regarding a workflow to follow when using the h2m converting tool.

One of them is to always include `index.html` on the file path to prevent the tool from recursing into all eventual subdirectories.

Nonetheless, I've noticed that when I run, for instance  `yarn md h2m web/javascript/guide/grammar_and_types/index.html --locale pt-BR --mode dry` (with the index.html on the life path), this is the output:

```
Done in 11.09s.
```

No errors. No logs. 

And I get a different outcome when I run `yarn md h2m web/javascript/guide/grammar_and_types --locale pt-BR --mode dry`:

```
Could not automatically convert 17 elements. Saving report to md-conversion-problems-report-2022-07-30T19_23_37.881Z.md
Done in 10.30s.
```

In fact, running it in replace mode with the `index.html` in the file path, I get no effect at all, although receiving a "done" message. Everything works fine when specifying just the folder.

Probably better to look into this to put it on the docs and prevent doubts/errors from contributors in oncoming community efforts of mass conversion.

cc @schalkneethling

**Comment by yin1999** [comment]
Hi @bpires, this tool is used for batch convertion (I think). You can view this line:

https://github.com/mdn/markdown/blob/a14082ac02739de16fed4eb276becfa5754ab614/src/cli.js#L131

**Comment by bpires** [comment]
Thanks @yin1999 for taking the time to provide this clarification! I guess this would be more of a question to be taken into consideration by @schalkneethling in the next events. 

The guidelines for using the tool (https://pad.mozilla.org/p/mdn-markdown-hack-day) have to reckon that you can't specify the .html file to be converted. 

This would be annoying if you are converting a folder containing a .html file and other subfolders with more .html files in them, as the only current viable option is for the tool to batch-convert them all.

**Comment by queengooborg** [comment]
Hey @bpires -- I actually have fixed this in the commit linked above, so now a specific file can be specified rather than an entire folder.

**Comment by bpires** [comment]
Awesome! Thanks @queengooborg you rock! 😃 I did not see it, my bad!
