### ISSUE TITLE
markdown convertion err

### ISSUE THREAD

**Issue by hochan222** [mdn/markdown#55]
Conversion is not possible for files with the following folder names. It's probably because there is `(`, `)`

- descriptor_(css)

```bash
yarn h2m glossary/descriptor_(css) --locale ko --mode keep
zsh: number expected
```

<img width="654" alt="image" src="https://user-images.githubusercontent.com/22424891/184378836-1fc5a608-5558-4a93-a016-6a8057f60f74.png">

**Comment by queengooborg** [comment]
This is an issue with `zsh`, not the converter.  You can bypass the `zsh` parsing by surrounding the folder name in quotes.

**Comment by hochan222** [comment]
I couldn't check the error message in a hurry. I'm ashamed. Thank you for caring me :)
