### ISSUE TITLE
markdown convertion `<a>` error

### ISSUE THREAD

**Issue by hochan222** [mdn/markdown#66]
- html
  - `<a href="/en -US/docs/Tools/Page_Inspector#How_to">방법 안내</a>`
```
<h2 id="Find_out_more_about_the_Firefox_DevTools">Firefox DevTools에 대해 자세히 알아보기</h2>

<p>여기 MDN에 Firefox DevTools에 대한 많은 정보가 있습니다. 주요 <a href="/en-US/docs/Tools">DevTools 섹션</a>을 살펴보고 이 강의에서 간략하게 다룬 내용에 대한 자세한 내용은 <a href="/en -US/docs/Tools/Page_Inspector#How_to">방법 안내</a>.</p>
```

- convert html to md
  - `[방법 안내](</en -US/docs/Tools/Page_Inspector#How_to>)`
```
## Firefox DevTools에 대해 자세히 알아보기

여기 MDN에 Firefox DevTools에 대한 많은 정보가 있습니다. 주요 [DevTools 섹션](/ko/docs/Tools)을 살펴보고 이 강의에서 간략하게 다룬 내용에 대한 자세한 내용은 [방법 안내](</en -US/docs/Tools/Page_Inspector#How_to>).
```

- expect
  - `[방법 안내](/en-US/docs/Tools/Page_Inspector#How_to)`
```
## Firefox DevTools에 대해 자세히 알아보기

여기 MDN에 Firefox DevTools에 대한 많은 정보가 있습니다. 주요 [DevTools 섹션](/ko/docs/Tools)을 살펴보고 이 강의에서 간략하게 다룬 내용에 대한 자세한 내용은 [방법 안내](/en-US/docs/Tools/Page_Inspector#How_to).
```

**Comment by queengooborg** [comment]
This is actually a proper conversion -- if you look carefully, you can see that there's a space in the original URL.  Markdown uses angle brackets like quotes in a link to escape a URL with normally invalid characters.

**Comment by hochan222** [comment]
I understand. Thanks for the explanation.
